= opengb.spork.dgrid

- dgrid state represented as a map containing "first class" cols, rows and cells.
- keeps the managing of dgrid state separate from the persistence/reactivity
  strategy (currently supporting either a reagent ratom or re-frame app-db).
- "headless," meaning the intention is that the user write a relatively
  straightforward custom hiccup-based component for the UI, and this library
  will concern itself with providing accessors and mutators for a data
  structure that keeps the state consistent.
- inspired by react-table and d3, which provide useful generalized functions
  around data but leave the DOM representation entirely up to you.

glossary + big concepts

the big idea is that we have columns and rows as first-class structures, and
what we toss into making a datagrid should require minimal processing.
we supply some minimal columns as maps
we supply data as either:
a) a seq of sequentials (ie. a vector of floats, like what you'd get from a CSV) or
b) a seq of maps

a "datagrid" refers to this headless data structure ... a big nested map
here with no UI dependencies.

a "table" refers to an HTML table UI (or something similar like nested divs)

"data" is raw rows (vector of x or map k:x) supplied by user

a "raw column" is supplied by a user and is supplemented by make-datagrid-inst

header, row, cell are vended by the table instance and are model objects
with properties to help with display via hiccup (eg. props, render fns that
generate hiccup)

a "header" is the th equivalent of a td "cell" and acts similarly (meant for UI)

== example

[source,clojure]
----
include::example.clj
----

== models

=== dgrid

=== row

=== col

=== cell

== accessors

=== props

== mutation

=== sorting

=== filtering

=== pagination
